### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by syntaxcat**

### CODE REVIEW

**Comment by mxvrnv** [comment]
Do we also want to remove the `logo.svg` file? I think it's not used anymore.

**Comment by mxvrnv** [comment]
Let's change the title in `index.html` to match our new app name 😉

**Comment by mxvrnv** [comment]
I think the `App.test.tsx` can be removed too. Right now it fails.

**Comment by syntaxcat** [comment]
@mxvrnv 
I addressed all of your comments.

Please note:
instead of removing the test file - I updated it so it won't fail.

**Review by mxvrnv — APPROVED** [review]
Good job! 🎉 

Please squash and rebase on main before you merge.

**Pull request merged**
